//
//  ViewController.swift
//  Weather App - L6
//
//  Created by Iván González Acuña on 01/10/2019.
//  Copyright © 2019 Iván González Acuña. All rights reserved.
//

import UIKit

class ViewController: UIViewController, callbackInterface {
    
    func printData(weatherData: WeatherClass) {
        DispatchQueue.main.async {
            self.imageView.image = UIImage(named: weatherData.icon)
            weatherData.temp = weatherData.temp - 273.15
            let tempAux = String(format: "%.1f", weatherData.temp)
            self.tempLabel.text = String(tempAux) + "°C"
            self.forecastLabel.text = weatherData.forecast
        }
    }

    @IBOutlet weak var textField: UITextField!
    @IBOutlet weak var tempLabel: UILabel!
    @IBOutlet weak var forecastLabel: UILabel!
    @IBOutlet weak var imageView: UIImageView!
    var temp: Float = 0
    var icon: String = ""
    var forecast: String = ""
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }

    @IBAction func getWeather(_ sender: Any) {
        let city = textField.text!
        
        let weatherObject : WeatherClass = WeatherClass(city: city, cb: self as callbackInterface)
        weatherObject.run()
    }
}

protocol callbackInterface {
    func printData(weatherData: WeatherClass) -> Void
}

class WeatherClass :Thread {
    
    var city: String = ""
    var temp: Float = 0
    var icon: String = ""
    var forecast: String = ""
    
    struct Data: Codable { // or Decodable
        struct Weather : Codable {
            let icon: String
            let main: String
        }
        struct Main : Codable {
            let temp: Float
        }
        
        let weather: [Weather]
        let main: Main
    }
    
    var callback : callbackInterface
    
    init(city: String, cb : callbackInterface) {
        self.city = city
        callback = cb
    }
    
    func run() {
    
        if let urlAPI = URL(string: "https://api.openweathermap.org/data/2.5/weather?q=" + city + "&APPID=65dbec3aae5e5bf9000c7a956c8b76f6")  {
            URLSession.shared.dataTask(with: urlAPI) { data, response, error in
                if let data = data {
                    do {
                        let res = try JSONDecoder().decode(Data.self, from: data)
                        self.temp = res.main.temp
                        self.icon = res.weather[0].icon
                        self.forecast = res.weather[0].main
    
                        if let urlImage = URL(string: "https://openweathermap.org/img/w/" + self.icon + ".png") {
                            URLSession.shared.dataTask(with: urlImage, completionHandler: { (data, response, error) in
    
                                if error != nil {
                                    print(error!)
                                    return
                                }
                                // We can´t send the Data type generated by the URLSession.
                                // So it´s impossible to print the imageView in this code.
                                // We don+t know how to pass properly Data.
                                self.callback.printData(weatherData: self)
                            }).resume()
                        }
                    } catch let error {
                        print(error)
                    }
                }
            }.resume()
        }
    }
}




